# [target.aarch64-linux-android]
# ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\arm64\\bin\\aarch64-linux-android-ar"
# linker = "C:\\Users\\dan-gl\\.rustup\\toolchains\\arm64\\bin\\aarch64-linux-android26-clang.cmd"

# [target.armv7-linux-androideabi]
# ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\arm\\bin\\arm-linux-androideabi-ar"
# linker = "C:\\Users\\dan-gl\\.rustup\\toolchains\\arm\\bin\\arm-linux-androideabi26-clang.cmd"

# [target.i686-linux-android]
# ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\x86\\bin\\i686-linux-android-ar"
# linker = "C:\\Users\\dan-gl\\.rustup\\toolchains\\x86\\bin\\i686-linux-android26-clang.cmd"

# [target.x86_64-linux-android]
# ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\x86_64\\bin\\x86_64-linux-android-ar"
# linker = "C:\\Users\\dan-gl\\.rustup\\toolchains\\x86_64\\bin\\x86_64-linux-android26-clang.cmd"

[target.aarch64-linux-android]
ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\arm64\\bin\\aarch64-linux-android-ar"
linker = "C:\\Users\\dan-gl\\AppData\\Local\\Android\\Sdk\\ndk\\23.0.7599858\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android26-clang.cmd"

[target.armv7-linux-androideabi]
ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\arm\\bin\\arm-linux-androideabi-ar"
linker = "C:\\Users\\dan-gl\\AppData\\Local\\Android\\Sdk\\ndk\\23.0.7599858\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi26-clang.cmd"

[target.i686-linux-android]
ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\x86\\bin\\i686-linux-android-ar"
linker = "C:\\Users\\dan-gl\\AppData\\Local\\Android\\Sdk\\ndk\\23.0.7599858\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\i686-linux-android26-clang.cmd"

[target.x86_64-linux-android]
ar = "C:\\Users\\dan-gl\\.rustup\\toolchains\\x86_64\\bin\\x86_64-linux-android-ar"
linker = "C:\\Users\\dan-gl\\AppData\\Local\\Android\\Sdk\\ndk\\23.0.7599858\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android26-clang.cmd"
